#!/usr/bin/env bash
#
# ubuntu2404-setup.sh
# -------------------
# Initial environment setup script for a fresh Ubuntu 24.04 (Noble) install.
#
#   1) Change SSH port from 22 -> 6800 (handles both ssh.socket / ssh.service)
#   2) Install Docker Engine (official apt repository method)
#   3) Install Visual Studio Code & Google Chrome
#   4) Install Anaconda (auto-detects latest version, installs to user account)
#
# Usage:
#   chmod +x ubuntu2404-setup.sh
#   sudo ./ubuntu2404-setup.sh
#
# Notes:
#   - Must be run with sudo.
#   - After changing the SSH port, verify you can connect from a *new*
#     terminal with `ssh -p 6800 user@server` BEFORE logging out.
#
set -euo pipefail

# ===================== Configuration (edit as needed) =====================
SSH_PORT=6800                 # SSH port to switch to
REMOVE_OLD_SSH_PORT=true      # remove the old port 22 from the firewall after the change
                              # (only removed once port ${SSH_PORT} is confirmed listening)

# Per-step on/off switches (set to false to skip a given step)
DO_SSH=true
DO_DOCKER=true
DO_APPS=true        # VSCode + Chrome
DO_ANACONDA=true
# ==========================================================================

LOG_FILE="/var/log/ubuntu2404-setup.log"

# ----------------------- Helper functions ---------------------------
log()  { echo -e "\n\033[1;32m[+]\033[0m $*"; }
warn() { echo -e "\033[1;33m[!]\033[0m $*"; }
err()  { echo -e "\033[1;31m[x]\033[0m $*" >&2; }

# Mirror all output to the log file as well
exec > >(tee -a "$LOG_FILE") 2>&1

# Check for root privileges
if [[ $EUID -ne 0 ]]; then
  err "This script requires root privileges. Run it with 'sudo $0'."
  exit 1
fi

# Determine the real user (the sudo caller) - used for Anaconda install / group membership
TARGET_USER="${SUDO_USER:-root}"
TARGET_HOME="$(getent passwd "$TARGET_USER" | cut -d: -f6)"
if [[ -z "$TARGET_HOME" ]]; then
  TARGET_HOME="/root"
fi

# Detect architecture
DPKG_ARCH="$(dpkg --print-architecture)"   # amd64 / arm64 ...
case "$DPKG_ARCH" in
  amd64) ANACONDA_ARCH="x86_64" ;;
  arm64) ANACONDA_ARCH="aarch64" ;;
  *)     ANACONDA_ARCH="" ;;
esac

export DEBIAN_FRONTEND=noninteractive

log "Checking Ubuntu version"
. /etc/os-release
echo "    -> $PRETTY_NAME (arch: $DPKG_ARCH)"
if [[ "${VERSION_ID:-}" != "24.04" ]]; then
  warn "This script targets Ubuntu 24.04. Current version: ${VERSION_ID:-unknown}"
  warn "Continuing anyway, but some behavior may differ."
fi

log "Updating package lists and upgrading existing packages"
apt-get update -y
apt-get upgrade -y
apt-get install -y ca-certificates curl wget gnupg apt-transport-https lsb-release iproute2

# ============================================================
# 1) Change SSH port (22 -> $SSH_PORT)
# ============================================================
if [[ "$DO_SSH" == true ]]; then
  log "[1/4] Changing SSH port to ${SSH_PORT}"

  # Ensure openssh-server is installed
  apt-get install -y openssh-server

  # Back up the existing config
  BACKUP_TS="$(date +%Y%m%d-%H%M%S)"
  cp -a /etc/ssh/sshd_config "/etc/ssh/sshd_config.bak.${BACKUP_TS}"
  echo "    -> Backup: /etc/ssh/sshd_config.bak.${BACKUP_TS}"

  # Set the port via a drop-in config file (Include in sshd_config takes precedence)
  install -d -m 0755 /etc/ssh/sshd_config.d
  cat > /etc/ssh/sshd_config.d/99-custom-ssh-port.conf <<EOF
# Generated by ubuntu2404-setup.sh (${BACKUP_TS})
Port ${SSH_PORT}
EOF
  echo "    -> Created /etc/ssh/sshd_config.d/99-custom-ssh-port.conf"

  # Ubuntu 24.04 uses socket-based activation (ssh.socket) by default.
  # When the socket is enabled, the Port in sshd_config is ignored,
  # so a socket override is required.
  if systemctl is-enabled ssh.socket >/dev/null 2>&1 || systemctl is-active ssh.socket >/dev/null 2>&1; then
    echo "    -> ssh.socket detected: updating the socket listening port as well"
    install -d -m 0755 /etc/systemd/system/ssh.socket.d
    cat > /etc/systemd/system/ssh.socket.d/override.conf <<EOF
[Socket]
ListenStream=
ListenStream=${SSH_PORT}
EOF
    systemctl daemon-reload
  fi

  # Validate the configuration syntax
  if ! sshd -t; then
    err "sshd config validation failed. Aborting SSH changes. Check the backup file."
    exit 1
  fi

  # If a firewall (ufw) is present, allow the new port first
  if command -v ufw >/dev/null 2>&1; then
    ufw allow "${SSH_PORT}/tcp" || true
    echo "    -> ufw: allowed ${SSH_PORT}/tcp"
  fi

  # Restart the service (existing connections are not dropped)
  systemctl restart ssh.socket 2>/dev/null || true
  systemctl restart ssh 2>/dev/null || true

  # Give the service a moment to come up, then verify the new port is listening
  sleep 2
  SSH_PORT_LISTENING=false
  if ss -ltn 2>/dev/null | grep -qE "[:.]${SSH_PORT}\b"; then
    SSH_PORT_LISTENING=true
    echo "    -> Confirmed: SSH is now listening on port ${SSH_PORT}"
  else
    err "SSH does not appear to be listening on port ${SSH_PORT}."
    err "Keeping port 22 open as a fallback. Investigate before closing it."
  fi

  # Remove the old port 22 only after the new port is confirmed working
  if [[ "$REMOVE_OLD_SSH_PORT" == true ]]; then
    if [[ "$SSH_PORT_LISTENING" == true ]]; then
      if command -v ufw >/dev/null 2>&1; then
        ufw delete allow 22/tcp || true
        ufw delete allow OpenSSH || true
        echo "    -> ufw: removed the old port 22 rules"
      else
        warn "ufw is not installed; cannot remove port 22 from a firewall."
        warn "If another firewall is in use, remove port 22 manually."
      fi
    else
      warn "Skipping port 22 removal because port ${SSH_PORT} is not confirmed."
    fi
  fi

  warn "SSH port has been changed to ${SSH_PORT}."
  warn "Before closing this session, be sure to test the connection from a new terminal:"
  warn "    ssh -p ${SSH_PORT} ${TARGET_USER}@<server-address>"
else
  log "[1/4] Skipping SSH step (DO_SSH=false)"
fi

# ============================================================
# 2) Install Docker Engine (official apt repository)
#    Reference: https://docs.docker.com/engine/install/ubuntu/
# ============================================================
if [[ "$DO_DOCKER" == true ]]; then
  log "[2/4] Installing Docker Engine"

  # Remove potentially conflicting packages
  for pkg in docker.io docker-compose docker-compose-v2 docker-doc podman-docker; do
    apt-get remove -y "$pkg" >/dev/null 2>&1 || true
  done

  # Register Docker's official GPG key
  install -m 0755 -d /etc/apt/keyrings
  if [[ ! -f /etc/apt/keyrings/docker.asc ]]; then
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
    chmod a+r /etc/apt/keyrings/docker.asc
  fi

  # Add the apt repository (deb822 format)
  cat > /etc/apt/sources.list.d/docker.sources <<EOF
Types: deb
URIs: https://download.docker.com/linux/ubuntu
Suites: ${UBUNTU_CODENAME:-$VERSION_CODENAME}
Components: stable
Signed-By: /etc/apt/keyrings/docker.asc
EOF

  apt-get update -y
  apt-get install -y docker-ce docker-ce-cli containerd.io \
                     docker-buildx-plugin docker-compose-plugin

  systemctl enable --now docker

  # Add the regular user to the docker group so they can use docker without sudo
  if [[ "$TARGET_USER" != "root" ]]; then
    usermod -aG docker "$TARGET_USER"
    echo "    -> Added user '${TARGET_USER}' to the docker group (effective after re-login)"
  fi

  docker --version || true
else
  log "[2/4] Skipping Docker step (DO_DOCKER=false)"
fi

# ============================================================
# 3) Install VSCode & Google Chrome
# ============================================================
if [[ "$DO_APPS" == true ]]; then
  log "[3/4] Installing VSCode & Google Chrome"

  # ---- VSCode (Microsoft's official apt repository) ----
  log "Installing VSCode"
  TMP_MS_KEY="$(mktemp)"
  wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > "$TMP_MS_KEY"
  install -D -o root -g root -m 644 "$TMP_MS_KEY" /etc/apt/keyrings/packages.microsoft.gpg
  rm -f "$TMP_MS_KEY"
  cat > /etc/apt/sources.list.d/vscode.list <<EOF
deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main
EOF
  apt-get update -y
  apt-get install -y code
  echo "    -> VSCode installed"

  # ---- Google Chrome (official .deb) ----
  if [[ "$DPKG_ARCH" == "amd64" ]]; then
    log "Installing Google Chrome"
    TMP_CHROME="$(mktemp --suffix=.deb)"
    wget -q -O "$TMP_CHROME" \
      https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    apt-get install -y "$TMP_CHROME"
    rm -f "$TMP_CHROME"
    echo "    -> Chrome installed (will auto-update on subsequent apt updates)"
  else
    warn "Google Chrome only supports amd64. Skipping on this architecture (${DPKG_ARCH})."
    warn "On ARM, consider using Chromium instead: apt-get install -y chromium-browser"
  fi
else
  log "[3/4] Skipping apps (VSCode/Chrome) step (DO_APPS=false)"
fi

# ============================================================
# 4) Install Anaconda (installed under the user account)
# ============================================================
if [[ "$DO_ANACONDA" == true ]]; then
  log "[4/4] Installing Anaconda"

  if [[ -z "$ANACONDA_ARCH" ]]; then
    warn "Unsupported architecture (${DPKG_ARCH}) - skipping Anaconda install."
  elif [[ "$TARGET_USER" == "root" ]]; then
    warn "Could not determine a regular user (sudo caller) - skipping Anaconda install."
    warn "Re-run with 'sudo' from a regular user account."
  else
    # Libraries needed to run GUI packages such as Navigator
    apt-get install -y libgl1 libegl1 libxrandr2 libxss1 libxcursor1 \
                       libxcomposite1 libasound2t64 libxi6 libxtst6 || true

    # Auto-detect the latest Anaconda installer filename
    log "Searching for the latest Anaconda installer..."
    INSTALLER_NAME="$(curl -fsSL https://repo.anaconda.com/archive/ \
      | grep -oE "Anaconda3-[0-9]{4}\.[0-9]{2}-[0-9]+-Linux-${ANACONDA_ARCH}\.sh" \
      | sort -V | tail -n 1)"

    if [[ -z "$INSTALLER_NAME" ]]; then
      err "Could not find an Anaconda installer. Check your network connection."
    else
      INSTALLER_URL="https://repo.anaconda.com/archive/${INSTALLER_NAME}"
      INSTALLER_PATH="/tmp/${INSTALLER_NAME}"
      ANACONDA_DIR="${TARGET_HOME}/anaconda3"
      echo "    -> Target: ${INSTALLER_NAME}"

      wget -q -O "$INSTALLER_PATH" "$INSTALLER_URL"

      if [[ -d "$ANACONDA_DIR" ]]; then
        warn "${ANACONDA_DIR} already exists. Skipping Anaconda reinstall."
      else
        # Install in batch mode as the target user
        sudo -u "$TARGET_USER" bash "$INSTALLER_PATH" -b -p "$ANACONDA_DIR"
        # conda init (adds conda to the user's shell config)
        sudo -u "$TARGET_USER" "$ANACONDA_DIR/bin/conda" init bash
        echo "    -> Anaconda installed: ${ANACONDA_DIR}"
        echo "    -> Open a new terminal or run 'source ~/.bashrc' to start using conda"
      fi
      rm -f "$INSTALLER_PATH"
    fi
  fi
else
  log "[4/4] Skipping Anaconda step (DO_ANACONDA=false)"
fi

# ============================================================
# Completion summary
# ============================================================
log "All tasks complete!"
cat <<EOF

────────────────────────────────────────────────
 Installation summary
────────────────────────────────────────────────
 SSH port      : $([[ "$DO_SSH" == true ]] && echo "changed to ${SSH_PORT}$([[ "$REMOVE_OLD_SSH_PORT" == true ]] && echo ", port 22 removal attempted")" || echo "skipped")
 Docker        : $([[ "$DO_DOCKER" == true ]] && echo "installed" || echo "skipped")
 VSCode/Chrome : $([[ "$DO_APPS" == true ]] && echo "installed" || echo "skipped")
 Anaconda      : $([[ "$DO_ANACONDA" == true ]] && echo "install attempted" || echo "skipped")

 Log file      : ${LOG_FILE}
────────────────────────────────────────────────

 Please check the following:
  1) [IMPORTANT] Test the SSH connection from a new terminal:
       ssh -p ${SSH_PORT} ${TARGET_USER}@<server-address>
     Port 22 may already be closed in the firewall, so the old port
     will likely no longer work. Confirm the new port before logging out.
  2) Re-login (or run 'newgrp docker') for docker group membership to take effect
  3) Run 'source ~/.bashrc' or open a new terminal to use the conda command
────────────────────────────────────────────────
EOF
